[tool.poetry]
name = "proyecto1"
version = "0.1.0"
description = "Proyecto 01ean machine learning"
authors = ["Javier callejas cardozo <javie.cardozo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
