[tool.poetry]
name = "proyecto1"
version = "0.1.0"
description = "Proyecto 01ean machine learning"
authors = ["Javier callejas cardozo <javie.cardozo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
matplotlib = "^3.9.2"
scikit-learn = "^1.5.2"
numpy = "^2.1.2"
seaborn = "^0.13.2"
scipy = "^1.14.1"
xgboost = "^2.1.1"
torch = "^2.4.1"
lightgbm = "^4.5.0"
joblib = "^1.4.2"
plotly = "^5.24.1"
statsmodels = "^0.14.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
